apiVersion: v1
kind: Service
metadata:
  name: contestant-exchange
  namespace: evaluation-sandbox
  labels:
    app: contestant-exchange
spec:
  type: ClusterIP
  selector:
    app: contestant-exchange
  ports:
    - name: websocket
      protocol: TCP
      port: 8080
      targetPort: websocket
